name: Build Spigot Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with javac
      run: |
        mkdir -p build
        javac -d build -sourcepath src src/me/vertox/welcome/WelcomePlugin.java

    - name: Copy plugin.yml
      run: cp plugin.yml build/

    - name: Create JAR
      run: |
        cd build
        jar cf ../WelcomePlugin.jar *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WelcomePlugin
        path: WelcomePlugin.jar
